"""Type stubs for python-snappy."""

from typing import IO, overload

__version__: str

class UncompressError(Exception): ...

def compress(data: bytes | str, encoding: str = ...) -> bytes: ...

@overload
def uncompress(data: bytes, decoding: str) -> str: ...
@overload
def uncompress(data: bytes, decoding: None = ...) -> bytes: ...

@overload
def decompress(data: bytes, decoding: str) -> str: ...
@overload
def decompress(data: bytes, decoding: None = ...) -> bytes: ...

def isValidCompressed(data: bytes | str) -> bool: ...

class StreamCompressor:
    def add_chunk(self, data: bytes, compress: object = ...) -> bytes: ...
    def compress(self, data: bytes, compress: object = ...) -> bytes: ...
    def flush(self) -> bytes: ...
    def copy(self) -> StreamCompressor: ...

class StreamDecompressor:
    @staticmethod
    def check_format(fin: IO[bytes]) -> bool: ...
    def decompress(self, data: bytes) -> bytes: ...
    def flush(self) -> bytes: ...
    def copy(self) -> StreamDecompressor: ...

class HadoopStreamCompressor:
    def add_chunk(self, data: bytes, compress: object = ...) -> bytes: ...
    def compress(self, data: bytes, compress: object = ...) -> bytes: ...
    def flush(self) -> bytes: ...
    def copy(self) -> HadoopStreamCompressor: ...

class HadoopStreamDecompressor:
    @staticmethod
    def check_format(fin: IO[bytes]) -> bool: ...
    def decompress(self, data: bytes) -> bytes: ...
    def flush(self) -> bytes: ...
    def copy(self) -> HadoopStreamDecompressor: ...

def stream_compress(
    src: IO[bytes],
    dst: IO[bytes],
    blocksize: int = ...,
    compressor_cls: type[StreamCompressor] = ...,
) -> None: ...

def stream_decompress(
    src: IO[bytes],
    dst: IO[bytes],
    blocksize: int = ...,
    decompressor_cls: type[StreamDecompressor] = ...,
    start_chunk: bytes | None = ...,
) -> None: ...
